Ajax/config/routes.rb
Rails.application.routes.draw do
  resources :ponies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Ajax/app/models/pony.rb
class Pony < ApplicationRecord
end

Ajax/app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: %i[ show edit update destroy ]

  # GET /ponies or /ponies.json
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1 or /ponies/1.json
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies or /ponies.json
  def create
    @pony = Pony.new(pony_params)

    respond_to do |format|
      if @pony.save
        format.html { redirect_to pony_url(@pony), notice: "Pony was successfully created." }
        format.json { render :show, status: :created, location: @pony }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponies/1 or /ponies/1.json
  def update
    respond_to do |format|
      if @pony.update(pony_params)
        format.html { redirect_to pony_url(@pony), notice: "Pony was successfully updated." }
        format.json { render :show, status: :ok, location: @pony }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponies/1 or /ponies/1.json
  def destroy
    @pony = Pony.find(params[:id])
    @pony.destroy

    # respond_to do |format|
    #   format.html { redirect_to ponies_url, notice: "Pony was successfully destroyed." }
    #   format.json { head :no_content }
    # end
    respond_to do |format|
      format.html { redirect_to ponies_url, notice: "Pony was successfully destroyed."  }
      format.json { head :no_content }
      format.js   { render :layout => false }
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pony_params
      params.require(:pony).permit(:name, :profession)
    end
end

Ajax/app/helpers/ponies_helper.rb
module PoniesHelper
end

Ajax/app/views/ponies/_form.html.erb
<%= form_with(model: pony) do |form| %>
  <% if pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
        <% pony.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :profession %>
    <%= form.text_field :profession %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Ajax/app/views/ponies/destroy.js.erb
$('.delete_pony').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

$(document).ready(function(){
    console.log("hii")
})

Ajax/app/views/ponies/edit.html.erb
<h1>Editing Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Show', @pony %> |
<%= link_to 'Back', ponies_path %>

Ajax/app/views/ponies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ponies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name %></td>
        <td><%= pony.profession %></td>
        <td><%= link_to 'Show', pony %></td>
        <td><%= link_to 'Edit', edit_pony_path(pony) %></td>
        <td><%= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' },
          remote: true , class: 'delete_pony'
        %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pony', new_pony_path %>

Ajax/app/views/ponies/new.html.erb
<h1>New Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Back', ponies_path %>

Ajax/app/views/ponies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @pony.profession %>
</p>

<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%= link_to 'Back', ponies_path %>