Snake/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post '/user' => 'home#create'
  get 'log_out' => 'home#destroy' , as: 'log_out'

  get 'join_game' => 'games#index' , as: 'join_game'
end

Snake/app/models/user.rb
class User < ApplicationRecord
end

Snake/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user   
        User.where(id: session[:user_id]).first 
    end   
    helper_method :current_user 
end

Snake/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    def create
        @user = User.find_by_email(params[:email])   
        if @user   
            session[:user_id] = @user.id   
            redirect_to root_path,notice:"User successfully logged in."
        else   
            @user = User.new(name:params[:name],email:params[:email])
            if @user.save
                session[:user_id] = @user.id  
                redirect_to root_path,notice:"New User Created."
            else 
                redirect_to root_path, notice:"Unable to create User. Please try again."
            end
        end  
    end
    def destroy
        session[:user_id] = nil   
        redirect_to root_url,notice:"User Logged Out."  
    end
end

Snake/app/views/home/index.html.erb
<br>
<br>
<br>
<%= flash[:notice] %>
<br>

<% if current_user %>
    Logged in as <%= current_user.email %> and <%= current_user.name %>
    <%= link_to "Log Out", log_out_path %>

    <%= link_to "Want to Join a Game", join_game_path %>
<% else %>  
    <%= render 'shared/login' %>
<% end %> 